name: nlp5290
channels:
  - pytorch
  - conda-forge
dependencies:
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cpython=3.11.14
  - filelock=3.20.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - jinja2=3.1.6
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=21.1.4
  - libdeflate=1.24
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libtiff=4.7.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.5
  - numpy=2.3.4
  - openjpeg=2.5.4
  - openssl=3.5.4
  - pillow=11.3.0
  - pip=25.2
  - pthread-stubs=0.4
  - pysocks=1.7.1
  - python=3.11.14
  - python_abi=3.11
  - pytorch=2.5.1
  - pyyaml=6.0.3
  - readline=8.2
  - requests=2.32.5
  - setuptools=80.9.0
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - anyio==4.11.0
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.2.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.4.0
      - dimabsa==0.1.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - iniconfig==2.3.0
      - ipykernel==7.0.1
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lark==1.3.0
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.7
      - mistune==3.1.4
      - multidict==6.7.0
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pycparser==2.23
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.10.23
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - sympy==1.13.1
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.14
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/nlp5290
